import _AccessibleElement from './nodes/AccessibleElement';
import _ButtonElement from './nodes/ButtonElement';
import _CommandElement from './nodes/CommandElement';
import _CoreNode from './nodes/CoreNode';
import _EventDispatcher from './nodes/EventDispatcher';
import _InteractiveNode from './nodes/InteractiveNode';
import _TabsComponent from './nodes/TabsComponent';
import _WidgetElement from './nodes/WidgetElement';
export declare const AccessibleElement: typeof _AccessibleElement;
export declare const ButtonElement: typeof _ButtonElement;
export declare const CommandElement: typeof _CommandElement;
export declare const CoreNode: typeof _CoreNode;
export declare const EventDispatcher: typeof _EventDispatcher;
export declare const InteractiveNode: typeof _InteractiveNode;
export declare const WidgetElement: typeof _WidgetElement;
export declare const TabsComponent: typeof _TabsComponent;
export declare function auto(): Promise<void>;
